# Framework for running automated tests on OSB using Travis-CI, see https://github.com/OpenSourceBrain/osb-model-validation

dist: xenial

addons:
  apt:
    packages:
    - python-matplotlib 
    - python-tk
    - python-numpy 
    - python-scipy 
    - python-tornado
    - python-lxml
    - python-tables

language: python
python: 2.7

virtualenv:
    system_site_packages: true

env:
    - OMV_ENGINE=PyNEURON
    # - OMV_ENGINE=PyNEURON:7.6   # Note: NEURON is preinstalled below...
    - OMV_ENGINE=jNeuroML
    - OMV_ENGINE=jNeuroML_NEURON
    - OMV_ENGINE=jNeuroML_NetPyNE
    - OMV_ENGINE=jNeuroML_validate

install:     
    - pip install kiwisolver==1.1.0 #  Temporary, due to issues with 1.2.0
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation
    
    # Need to pre install NEURON so nrnivmodl can be run targeting mod files in a different directory
    - omv install NEURON
    - cd NEURON/test
    - /home/travis/neuron/nrn/x86_64/bin/nrnivmodl ../mod.files
    - ls -alt
    - cd ../..

script:
    - omv all -V
    
    
    

