# Framework for running automated tests on OSB using Travis-CI, see https://github.com/OpenSourceBrain/osb-model-validation

sudo: false

language: python
python: 2.7

env:
    - OMV_ENGINE=PyNEURON
    - OMV_ENGINE=jNeuroML
    - OMV_ENGINE=jNeuroML_NEURON
    - OMV_ENGINE=jNeuroML_validate

install: 
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation
    
    # Need to pre install NEURON so nrnivmodl can be run targeting mod files in a different directory
    - omv install NEURON
    - cd NEURON/test
    - /home/travis/neuron/nrn/x86_64/bin/nrnivmodl ../mod.files
    - ls -alt
    - cd ../..

script:
    - omv all -V
    
    
    

